### ISSUE TITLE
mismatch keys in checkpoint

### ISSUE THREAD

**Issue by linyq2117** [xmed-lab/AllSpark#3] opened 2024-04-01 13:21 UTC
Thanks for sharing this nice work.

However, when i try to reproduce the results using your provided checkpoints, it seems that the checkpoints does not match the model architecture.
```
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        Missing key(s) in state_dict: "module.decoder.allspark.map_in.0.weight", "module.decoder.allspark.map_in.0.bias", "module.decoder.allspark.attn_norm.weight", "module.decoder.allspark.attn_norm.bias", "module.decoder.allspark.attn.queue_ptr", "module.decoder.allspark.attn.kv_queue", "module.decoder.allspark.attn.q_u.weight", "module.decoder.allspark.attn.k_u.weight", "module.decoder.allspark.attn.v_u.weight", "module.decoder.allspark.attn.q_l2u.weight", "module.decoder.allspark.attn.k_l2u.weight", "module.decoder.allspark.attn.v_l2u.weight", "module.decoder.allspark.attn.out_u.weight", "module.decoder.allspark.attn.out_l2u.weight", "module.decoder.allspark.encoder_norm.weight", "module.decoder.allspark.encoder_norm.bias", "module.decoder.allspark.map_out.0.weight", "module.decoder.allspark.map_out.0.bias". 
        Unexpected key(s) in state_dict: "module.decoder.allspark.embeddings.patch_embeddings.weight", "module.decoder.allspark.embeddings.patch_embeddings.bias", "module.decoder.allspark.encoder.layer.0.attn_norm1.weight", "module.decoder.allspark.encoder.layer.0.attn_norm1.bias", "module.decoder.allspark.encoder.layer.0.attn.queue_ptr", "module.decoder.allspark.encoder.layer.0.attn.kv_queue", "module.decoder.allspark.encoder.layer.0.attn.query_u_u.weight", "module.decoder.allspark.encoder.layer.0.attn.key_u_u.weight", "module.decoder.allspark.encoder.layer.0.attn.value_u_u.weight", "module.decoder.allspark.encoder.layer.0.attn.query_l_u.weight", "module.decoder.allspark.encoder.layer.0.attn.key_l_u.weight", "module.decoder.allspark.encoder.layer.0.attn.value_l_u.weight", "module.decoder.allspark.encoder.layer.0.attn.out_u.weight", "module.decoder.allspark.encoder.layer.0.attn.out_l.weight", "module.decoder.allspark.encoder.layer.0.ffn_norm1.weight", "module.decoder.allspark.encoder.layer.0.ffn_norm1.bias", "module.decoder.allspark.encoder.layer.0.ffn1.fc1.weight", "module.decoder.allspark.encoder.layer.0.ffn1.fc1.bias", "module.decoder.allspark.encoder.layer.0.ffn1.fc2.weight", "module.decoder.allspark.encoder.layer.0.ffn1.fc2.bias", "module.decoder.allspark.encoder.layer.1.attn_norm1.weight", "module.decoder.allspark.encoder.layer.1.attn_norm1.bias", "module.decoder.allspark.encoder.layer.1.attn.queue_ptr", "module.decoder.allspark.encoder.layer.1.attn.kv_queue", "module.decoder.allspark.encoder.layer.1.attn.query_u_u.weight", "module.decoder.allspark.encoder.layer.1.attn.key_u_u.weight", "module.decoder.allspark.encoder.layer.1.attn.value_u_u.weight", "module.decoder.allspark.encoder.layer.1.attn.query_l_u.weight", "module.decoder.allspark.encoder.layer.1.attn.key_l_u.weight", "module.decoder.allspark.encoder.layer.1.attn.value_l_u.weight", "module.decoder.allspark.encoder.layer.1.attn.out_u.weight", "module.decoder.allspark.encoder.layer.1.attn.out_l.weight", "module.decoder.allspark.encoder.layer.1.ffn_norm1.weight", "module.decoder.allspark.encoder.layer.1.ffn_norm1.bias", "module.decoder.allspark.encoder.layer.1.ffn1.fc1.weight", "module.decoder.allspark.encoder.layer.1.ffn1.fc1.bias", "module.decoder.allspark.encoder.layer.1.ffn1.fc2.weight", "module.decoder.allspark.encoder.layer.1.ffn1.fc2.bias", "module.decoder.allspark.encoder.encoder_norm1.weight", "module.decoder.allspark.encoder.encoder_norm1.bias", "module.decoder.allspark.recon.conv.weight", "module.decoder.allspark.recon.conv.bias".
```
Is this problem caused by the incorrect allspark checkpoints, or my misuse? If possible, could you provide a evaluation script to reproduce the results?

**Comment by Elliot-QxZhang** [comment] 2024-04-01 13:45
Hi, thank you so much for pointing out this mistake, and we are sorry for this carelessness. We believe this is because some of our weights are trained before we reorganize our codes, which causes this incompatibility. We will re-run and release them ASAP (no later than the main conference day). BTW, we have thoroughly checked the previously released weights, and all COCO weights as well as the PASCAL VOC (1/8)  are correct.

**Comment by linyq2117** [comment] 2024-04-02 08:19
Thanks for your reply.

I tried to train models from scratch following the default configs, but the result is lower than the reported, (e.g., I got 74.43 mIoU for the 92 setting on VOC, and 77.27  mIoU for the 1/16 setting on VOCAug). Is this normal? Could the current model configs produce the same performance as previous codes?

**Comment by Elliot-QxZhang** [comment] 2024-04-05 11:32
> Thanks for your reply.
> 
> I tried to train models from scratch following the default configs, but the result is lower than the reported, (e.g., I got 74.43 mIoU for the 92 setting on VOC, and 77.27 mIoU for the 1/16 setting on VOCAug). Is this normal? Could the current model configs produce the same performance as previous codes?

Hi, sorry for the late response. We were checking and rerunning the reorganized codes. These results are not normal, which may be caused by a small mistake due to the rushed release of the current pre-print version (we accidentally deleted the temperature coefficient for calculating similarities with semantic memory). We have released the correct weights and the training log for your reference. Also to increase the reproducibility, we have added the seed setup.  Both of these two code revisions will be released very soon.

**Comment by linyq2117** [comment] 2024-04-07 02:43
Thanks for your sincere response! Look forward to your updated version. BTW, could you share the expected release time?

**Comment by Elliot-QxZhang** [comment] 2024-04-08 02:06
Thanks for being interested in our work. We are currently rerunning and checking other parts of the codes for potential mistakes. The final version will be released in one to two weeks.

**Comment by linyq2117** [comment] 2024-04-09 04:53
Thanks for your patience!

**Closed as completed** 2024-06-16 02:50 UTC
Labels: no-issue-activity

**Comment by haruishi43** [comment] 2025-01-17 02:30
@linyq2117 have you reproduced the results of AllSpark?
@Elliot-QxZhang are there any updates on the final version?

**Comment by linyq2117** [comment] 2025-01-18 12:43
> [@linyq2117](https://github.com/linyq2117) have you reproduced the results of AllSpark? [@Elliot-QxZhang](https://github.com/Elliot-QxZhang) are there any updates on the final version?

Not yet. It seems that there is no update on the code.

**Comment by haruishi43** [comment] 2025-01-24 06:04
@linyq2117  Thanks for getting back to me! I hope they can update their code so we can try to reproduce their results.
